language: node_js
sudo: false
node_js:
    - "9"
os:
    - linux
    - osx
addons:
    firefox: latest
    chrome: stable
script:
    - npm test -- --verbose
cache:
    directories:
        - node_modules
# matrix:
#     exclude:
#         - os: osx # skip this because on Travis, node.js segfaults on osx+node 9
#           node_js: "9"
